## Q1. What are the different data structures used in Tensorflow?. Give some examplesc

### **Different Data Structures in TensorFlow**
TensorFlow provides several data structures to handle and manipulate data efficiently. The primary data structures include:

1. **Tensors (`tf.Tensor`)**  
2. **Variables (`tf.Variable`)**  
3. **Sparse Tensors (`tf.SparseTensor`)**  
4. **Ragged Tensors (`tf.RaggedTensor`)**  
5. **String Tensors (`tf.string`)**  
6. **Tensor Arrays (`tf.TensorArray`)**  
7. **Dataset API (`tf.data.Dataset`)**  

Let's go through each with examples:

---

### **1. Tensors (`tf.Tensor`)**
Tensors are multi-dimensional arrays (similar to NumPy arrays) that serve as the primary data structure in TensorFlow.

#### **Example: Creating Tensors**
```python
import tensorflow as tf

# Scalar (0D Tensor)
scalar = tf.constant(5)

# Vector (1D Tensor)
vector = tf.constant([1, 2, 3, 4])

# Matrix (2D Tensor)
matrix = tf.constant([[1, 2], [3, 4]])

# 3D Tensor
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Scalar:", scalar.numpy())
print("Vector:", vector.numpy())
print("Matrix:\n", matrix.numpy())
print("3D Tensor:\n", tensor_3d.numpy())
```

---

### **2. Variables (`tf.Variable`)**
A `tf.Variable` is a special type of tensor that allows modifications (e.g., for training parameters in deep learning).

#### **Example: Creating a Variable**
```python
# Creating a Variable Tensor
var_tensor = tf.Variable([[1.0, 2.0], [3.0, 4.0]])

# Modifying Variable
var_tensor.assign([[10.0, 20.0], [30.0, 40.0]])

print("Updated Variable Tensor:\n", var_tensor.numpy())
```

---

### **3. Sparse Tensors (`tf.SparseTensor`)**
Sparse tensors are used for handling data with a lot of zeros efficiently.

#### **Example: Creating a Sparse Tensor**
```python
sparse_tensor = tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[10, 20], dense_shape=[3, 4])

# Converting to dense format
dense_tensor = tf.sparse.to_dense(sparse_tensor)

print("Sparse Tensor (Dense Format):\n", dense_tensor.numpy())
```

---

### **4. Ragged Tensors (`tf.RaggedTensor`)**
Ragged tensors are used for handling data where rows have different lengths (e.g., variable-length sequences).

#### **Example: Creating a Ragged Tensor**
```python
ragged_tensor = tf.ragged.constant([[1, 2, 3], [4, 5], [6]])

print("Ragged Tensor:\n", ragged_tensor)
```

---

### **5. String Tensors (`tf.string`)**
TensorFlow supports string tensors, which can store textual data.

#### **Example: Creating a String Tensor**
```python
string_tensor = tf.constant(["TensorFlow", "is", "awesome"])
print("String Tensor:\n", string_tensor.numpy())
```

---

### **6. Tensor Arrays (`tf.TensorArray`)**
Tensor Arrays are used for dynamic-sized tensors, mainly in RNNs or loops.

#### **Example: Creating a TensorArray**
```python
tensor_array = tf.TensorArray(dtype=tf.float32, size=3)

# Writing values
tensor_array = tensor_array.write(0, 10.0)
tensor_array = tensor_array.write(1, 20.0)
tensor_array = tensor_array.write(2, 30.0)

# Reading values
print("TensorArray Elements:", tensor_array.read(0).numpy(), tensor_array.read(1).numpy(), tensor_array.read(2).numpy())
```

---

### **7. Dataset API (`tf.data.Dataset`)**
The `tf.data.Dataset` API is used for input pipelines in deep learning.

#### **Example: Creating a Dataset**
```python
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5])

for elem in dataset:
    print(elem.numpy())
```

---

### **Comparison Table**
| Data Structure        | Use Case |
|----------------------|------------------------|
| `tf.Tensor`         | Basic multi-dimensional arrays |
| `tf.Variable`       | Trainable parameters in models |
| `tf.SparseTensor`   | Efficient storage for sparse data |
| `tf.RaggedTensor`   | Handling variable-length sequences |
| `tf.string`         | Storing and processing text |
| `tf.TensorArray`    | Dynamic tensor storage (useful in loops) |
| `tf.data.Dataset`   | Efficient input pipeline for training |

---

### **Final Thoughts**
- **Use `tf.Tensor`** for general computations.
- **Use `tf.Variable`** when working with trainable weights.
- **Use `tf.SparseTensor`** for memory-efficient storage of sparse data.
- **Use `tf.RaggedTensor`** when handling sequences of different lengths.
- **Use `tf.string`** for text-based processing.
- **Use `tf.TensorArray`** when dealing with dynamic lists.
- **Use `tf.data.Dataset`** for efficient data loading.

---


In [1]:
import tensorflow as tf

# Scalar (0D Tensor)
scalar = tf.constant(5)

# Vector (1D Tensor)
vector = tf.constant([1, 2, 3, 4])

# Matrix (2D Tensor)
matrix = tf.constant([[1, 2], [3, 4]])

# 3D Tensor
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Scalar:", scalar.numpy())
print("Vector:", vector.numpy())
print("Matrix:\n", matrix.numpy())
print("3D Tensor:\n", tensor_3d.numpy())

Scalar: 5
Vector: [1 2 3 4]
Matrix:
 [[1 2]
 [3 4]]
3D Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
# Creating a Variable Tensor
var_tensor = tf.Variable([[1.0, 2.0], [3.0, 4.0]])

# Modifying Variable
var_tensor.assign([[10.0, 20.0], [30.0, 40.0]])

print("Updated Variable Tensor:\n", var_tensor.numpy())


Updated Variable Tensor:
 [[10. 20.]
 [30. 40.]]


In [4]:
sparse_tensor = tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[10, 20], dense_shape=[3, 4])

# Converting to dense format
dense_tensor = tf.sparse.to_dense(sparse_tensor)

print("Sparse Tensor (Dense Format):\n", dense_tensor.numpy())

Sparse Tensor (Dense Format):
 [[10  0  0  0]
 [ 0  0 20  0]
 [ 0  0  0  0]]


In [5]:
ragged_tensor = tf.ragged.constant([[1, 2, 3], [4, 5], [6]])

print("Ragged Tensor:\n", ragged_tensor)

Ragged Tensor:
 <tf.RaggedTensor [[1, 2, 3], [4, 5], [6]]>


In [6]:
tensor_array = tf.TensorArray(dtype=tf.float32, size=3)

# Writing values
tensor_array = tensor_array.write(0, 10.0)
tensor_array = tensor_array.write(1, 20.0)
tensor_array = tensor_array.write(2, 30.0)

# Reading values
print("TensorArray Elements:", tensor_array.read(0).numpy(), tensor_array.read(1).numpy(), tensor_array.read(2).numpy())


TensorArray Elements: 10.0 20.0 30.0


In [7]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5])

for elem in dataset:
    print(elem.numpy())


1
2
3
4
5


## Q2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an examplec

In [10]:
import tensorflow as tf

const_tensor= tf.constant([[1,2],[3,4]])
print(const_tensor.numpy())

[[1 2]
 [3 4]]


In [12]:
var_tensor= tf.Variable([[1,2],[3,4]])

print(var_tensor.numpy())

var_tensor.assign([[10,20],[30,40]])
print("Variable Tensor (After Update):\n", var_tensor.numpy())

# Incrementing values
var_tensor.assign_add([[1, 1], [1, 1]])
print("Variable Tensor (After Increment):\n", var_tensor.numpy())

[[1 2]
 [3 4]]
Variable Tensor (After Update):
 [[10 20]
 [30 40]]
Variable Tensor (After Increment):
 [[11 21]
 [31 41]]


## Q3. Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.

### **Matrix Operations in TensorFlow**
TensorFlow provides efficient methods for performing matrix operations, including **addition, multiplication, and element-wise operations**. Below is a step-by-step explanation of each operation with examples.

---

### **1. Matrix Addition in TensorFlow**
Matrix addition is performed element-wise, meaning corresponding elements in the matrices are summed.

#### **Example: Matrix Addition**
```python
import tensorflow as tf

# Define two matrices
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

# Perform matrix addition
result_add = tf.add(A, B)

print("Matrix A:\n", A.numpy())
print("Matrix B:\n", B.numpy())
print("Matrix Addition (A + B):\n", result_add.numpy())
```
#### **Output:**
```
Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]

Matrix Addition (A + B):
 [[ 6  8]
 [10 12]]
```

**Note:** You can also use the `+` operator for matrix addition:
```python
result_add = A + B
```

---

### **2. Matrix Multiplication in TensorFlow**
There are two types of multiplication:
1. **Dot Product (Matrix Multiplication)** → `tf.matmul(A, B)`
2. **Element-wise Multiplication** → `tf.multiply(A, B)`

#### **Example: Matrix Multiplication (`tf.matmul`)**
Matrix multiplication follows the rule:  
\[
C = A \times B
\]
where **the number of columns in A must match the number of rows in B**.

```python
# Define two matrices
A = tf.constant([[1, 2], [3, 4]])  # Shape (2,2)
B = tf.constant([[5, 6], [7, 8]])  # Shape (2,2)

# Perform matrix multiplication
result_matmul = tf.matmul(A, B)

print("Matrix Multiplication (A @ B):\n", result_matmul.numpy())
```

#### **Output:**
```
Matrix Multiplication (A @ B):
 [[19 22]
 [43 50]]
```

**Mathematical Breakdown:**
\[
\begin{bmatrix}1 & 2 \\ 3 & 4\end{bmatrix} \times \begin{bmatrix}5 & 6 \\ 7 & 8\end{bmatrix} =
\begin{bmatrix} (1*5 + 2*7) & (1*6 + 2*8) \\ (3*5 + 4*7) & (3*6 + 4*8) \end{bmatrix}
=
\begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}
\]

Alternatively, you can use the `@` operator:
```python
result_matmul = A @ B
```

---

### **3. Element-wise Operations in TensorFlow**
Element-wise operations operate on corresponding elements in two matrices.

#### **Example: Element-wise Multiplication (`tf.multiply`)**
```python
result_elemwise = tf.multiply(A, B)

print("Element-wise Multiplication (A * B):\n", result_elemwise.numpy())
```

#### **Output:**
```
Element-wise Multiplication (A * B):
 [[ 5 12]
 [21 32]]
```

**Mathematical Breakdown:**
\[
\begin{bmatrix}1 & 2 \\ 3 & 4\end{bmatrix} * \begin{bmatrix}5 & 6 \\ 7 & 8\end{bmatrix} =
\begin{bmatrix} (1*5) & (2*6) \\ (3*7) & (4*8) \end{bmatrix}
=
\begin{bmatrix} 5 & 12 \\ 21 & 32 \end{bmatrix}
\]

---

### **4. Other Element-wise Operations**
#### **Element-wise Subtraction**
```python
result_sub = tf.subtract(A, B)
print("Element-wise Subtraction (A - B):\n", result_sub.numpy())
```

#### **Element-wise Division**
```python
result_div = tf.divide(A, B)
print("Element-wise Division (A / B):\n", result_div.numpy())
```

---

### **Comparison of Operations**
| Operation  | Function in TensorFlow | Description |
|------------|-----------------------|-------------|
| **Addition** | `tf.add(A, B)` | Adds corresponding elements |
| **Multiplication** | `tf.matmul(A, B)` | Matrix multiplication (dot product) |
| **Element-wise Multiplication** | `tf.multiply(A, B)` | Multiplies corresponding elements |
| **Subtraction** | `tf.subtract(A, B)` | Subtracts corresponding elements |
| **Division** | `tf.divide(A, B)` | Divides corresponding elements |

---

### **Key Takeaways**
- **Matrix addition (`tf.add`)**: Adds corresponding elements.
- **Matrix multiplication (`tf.matmul`)**: Follows matrix multiplication rules (dot product).
- **Element-wise multiplication (`tf.multiply`)**: Multiplies corresponding elements.
- **TensorFlow supports both `@` and function calls for operations.**

Would you like me to demonstrate these operations on higher-dimensional tensors? 🚀

## PART 2

## Task 1

## Q1. Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display the values of matrix Ac

In [15]:
A=tf.random.normal(shape=(3,3))

In [17]:
A.numpy()

array([[ 0.29443341,  0.03216101,  0.8316411 ],
       [ 0.90290314, -0.59010607,  0.7740579 ],
       [-0.1289116 ,  0.91407514, -0.55127066]], dtype=float32)

## Q2. Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix B

In [21]:
B=tf.random.truncated_normal(shape=(4,4))

In [22]:
B.numpy()

array([[ 0.18031706, -0.7853258 ,  1.5492768 , -0.7342636 ],
       [ 0.91070765, -0.72954017, -0.6974368 , -0.1322951 ],
       [-1.2810537 , -0.06267222,  1.5350051 ,  0.25964367],
       [-0.509709  ,  0.4343712 , -0.93317854, -1.4063392 ]],
      dtype=float32)

## Q3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.

In [23]:
C= tf.random.normal(shape=(2,2), mean=3.0 , stddev=0.5)

In [26]:
C.numpy()

array([[2.749667 , 2.9704084],
       [3.2455213, 2.5528555]], dtype=float32)

## Q4 . Perform matrix addition between matrix A and matrix B, and store the result in matrix D.

In [27]:
import tensorflow as tf

# Create two matrices A and B with the same dimensions (3x3)
A = tf.random.normal(shape=(3, 3), mean=0.0, stddev=1.0)
B = tf.random.normal(shape=(3, 3), mean=0.0, stddev=1.0)

# Perform matrix addition
D = tf.add(A, B)

# Display results
print("Matrix A:\n", A.numpy())
print("Matrix B:\n", B.numpy())
print("Matrix D (A + B):\n", D.numpy())


Matrix A:
 [[ 0.6099785  -0.64012045  0.2952327 ]
 [-1.3046523   0.02058416 -1.1755198 ]
 [-0.5419992   0.21414027 -0.17201053]]
Matrix B:
 [[ 0.58586055 -0.23787217  0.1264405 ]
 [ 1.5192232   0.18050593 -0.20805345]
 [-0.09408098 -0.80051273 -1.4807844 ]]
Matrix D (A + B):
 [[ 1.195839   -0.87799263  0.4216732 ]
 [ 0.21457088  0.2010901  -1.3835733 ]
 [-0.6360802  -0.5863725  -1.652795  ]]


## Q5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [28]:
import tensorflow as tf

# Create matrix C (2x2) with values from a normal distribution (mean=3, stddev=0.5)
C = tf.random.normal(shape=(2, 2), mean=3.0, stddev=0.5)

# Create matrix D (2x2) to match C's columns for multiplication
D = tf.random.normal(shape=(2, 2), mean=0.0, stddev=1.0)

# Perform matrix multiplication
E = tf.matmul(C, D)

# Display results
print("Matrix C:\n", C.numpy())
print("Matrix D:\n", D.numpy())
print("Matrix E (C x D):\n", E.numpy())


Matrix C:
 [[3.1785846 3.069805 ]
 [2.9064624 3.2397382]]
Matrix D:
 [[-0.20341097  0.30649364]
 [ 0.80629694 -0.6842982 ]]
Matrix E (C x D):
 [[ 1.8286154 -1.126446 ]
 [ 2.0209846 -1.3261348]]


## Task 2

## Q1. Create a matrix F with dimensions 3x3, initialized with random values using TensorFlow's random_uniform functionc

In [29]:
import tensorflow as tf

# Create a 3x3 matrix with random values from a uniform distribution (range: 0 to 1)
F = tf.random.uniform(shape=(3, 3), minval=0.0, maxval=1.0)

# Convert to NumPy array and display the values
print("Matrix F:\n", F.numpy())


Matrix F:
 [[0.00466204 0.7297567  0.34906113]
 [0.50741255 0.32403052 0.4950415 ]
 [0.25981987 0.96751046 0.32091355]]


## Q2. Calculate the transpose of matrix F and store the result in matrix G.

In [30]:
G= tf.transpose(F)

In [31]:
G.numpy()

array([[0.00466204, 0.50741255, 0.25981987],
       [0.7297567 , 0.32403052, 0.96751046],
       [0.34906113, 0.4950415 , 0.32091355]], dtype=float32)

## Q3. Calculate the element-wise exponential of matrix F and store the result in matrix H

In [33]:
H=tf.exp(F)

In [34]:
H.numpy()

array([[1.0046729, 2.074576 , 1.4177358],
       [1.660988 , 1.3826895, 1.6405663],
       [1.2966965, 2.6313853, 1.3783864]], dtype=float32)

## Q4. Create a matrix I by concatenating matrix F and matrix G horizontallyc

In [36]:
I= tf.concat([F,G],axis=1)

In [37]:
I.numpy()

array([[0.00466204, 0.7297567 , 0.34906113, 0.00466204, 0.50741255,
        0.25981987],
       [0.50741255, 0.32403052, 0.4950415 , 0.7297567 , 0.32403052,
        0.96751046],
       [0.25981987, 0.96751046, 0.32091355, 0.34906113, 0.4950415 ,
        0.32091355]], dtype=float32)

## Q5. Create a matrix J by concatenating matrix F and matrix H vertically.

In [39]:
J= tf.concat([F,G],axis=0)

In [40]:
J.numpy()

array([[0.00466204, 0.7297567 , 0.34906113],
       [0.50741255, 0.32403052, 0.4950415 ],
       [0.25981987, 0.96751046, 0.32091355],
       [0.00466204, 0.50741255, 0.25981987],
       [0.7297567 , 0.32403052, 0.96751046],
       [0.34906113, 0.4950415 , 0.32091355]], dtype=float32)